[package]
name = "i3-move-workspace"
version = "0.1.0"
authors = ["Jack Guo <jackguo380@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.i3ipc]
version = "0.10.1"
features = ["i3-4-14"]

